export const PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard:view',
  
  PARTS_VIEW: 'parts:view',
  PARTS_CREATE: 'parts:create',
  PARTS_UPDATE: 'parts:update',
  PARTS_DELETE: 'parts:delete',

  CATEGORIES_VIEW: 'categories:view',
  CATEGORIES_CREATE: 'categories:create',
  CATEGORIES_UPDATE: 'categories:update',
  CATEGORIES_DELETE: 'categories:delete',

  SUPPLIERS_VIEW: 'suppliers:view',
  SUPPLIERS_CREATE: 'suppliers:create',
  SUPPLIERS_UPDATE: 'suppliers:update',
  SUPPLIERS_DELETE: 'suppliers:delete',

  WAREHOUSES_VIEW: 'warehouses:view',
  WAREHOUSES_CREATE: 'warehouses:create',
  WAREHOUSES_UPDATE: 'warehouses:update',
  WAREHOUSES_DELETE: 'warehouses:delete',

  INVENTORY_VIEW: 'inventory:view',
  INVENTORY_CREATE: 'inventory:create',
  INVENTORY_UPDATE: 'inventory:update',
  INVENTORY_ADJUST: 'inventory:adjust',

  IMPORTS_VIEW: 'imports:view',
  IMPORTS_CREATE: 'imports:create',
  IMPORTS_APPROVE: 'imports:approve',
  IMPORTS_COMPLETE: 'imports:complete',
  IMPORTS_CANCEL: 'imports:cancel',

  EXPORTS_VIEW: 'exports:view',
  EXPORTS_CREATE: 'exports:create',
  EXPORTS_APPROVE: 'exports:approve',
  EXPORTS_COMPLETE: 'exports:complete',
  EXPORTS_CANCEL: 'exports:cancel',

  STOCK_CHECK_VIEW: 'stock-check:view',
  STOCK_CHECK_CREATE: 'stock-check:create',
  STOCK_CHECK_COUNT: 'stock-check:count',
  STOCK_CHECK_COMPLETE: 'stock-check:complete',
  STOCK_CHECK_APPROVE: 'stock-check:approve',
  STOCK_CHECK_ADJUST: 'stock-check:adjust',
  STOCK_CHECK_CANCEL: 'stock-check:cancel',

  QUALITY_CHECK_VIEW: 'quality-check:view',
  QUALITY_CHECK_CREATE: 'quality-check:create',
  QUALITY_CHECK_UPDATE: 'quality-check:update',
  QUALITY_CHECK_START: 'quality-check:start',
  QUALITY_CHECK_RECORD_DEFECT: 'quality-check:record-defect',
  QUALITY_CHECK_COMPLETE: 'quality-check:complete',
  QUALITY_CHECK_ADJUST: 'quality-check:adjust',
  QUALITY_CHECK_CANCEL: 'quality-check:cancel',
  QUALITY_CHECK_REVIEW: 'quality-check:review',
  QUALITY_CHECK_RESOLVE: 'quality-check:resolve',

  REPORTS_VIEW: 'reports:view',
  REPORTS_EXPORT: 'reports:export',
  REPORT_INVENTORY: 'report:inventory',
  REPORT_IMPORT: 'report:import',
  REPORT_EXPORT: 'report:export',
  REPORT_STOCK_CHECK: 'report:stock-check',
  REPORT_QUALITY: 'report:quality',
  REPORT_SUPPLIER: 'report:supplier',
  REPORT_PART: 'report:part',
  REPORT_WAREHOUSE: 'report:warehouse',

  USERS_VIEW: 'users:view',
  USERS_CREATE: 'users:create',
  USERS_UPDATE: 'users:update',
  USERS_ACTIVATE: 'users:activate',
  USERS_DEACTIVATE: 'users:deactivate',
  USERS_RESET_PASSWORD: 'users:reset-password',

  ROLES_VIEW: 'roles:view',
  ROLES_CREATE: 'roles:create',
  ROLES_UPDATE: 'roles:update',
  ROLES_DELETE: 'roles:delete',
  ROLES_PERMISSIONS_UPDATE: 'roles:permissions-update',

  AUDIT_LOGS_VIEW: 'audit-logs:view',
  ADMIN_DASHBOARD_VIEW: 'admin:dashboard',
};

export const DEFAULT_ROLE_PERMISSIONS: Record<string, string[]> = {
  'Administrator': Object.values(PERMISSIONS),
  
  'Manager': [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PARTS_VIEW, PERMISSIONS.PARTS_UPDATE,
    PERMISSIONS.CATEGORIES_VIEW, PERMISSIONS.CATEGORIES_UPDATE,
    PERMISSIONS.SUPPLIERS_VIEW,
    PERMISSIONS.WAREHOUSES_VIEW, PERMISSIONS.WAREHOUSES_CREATE, PERMISSIONS.WAREHOUSES_UPDATE,
    PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.IMPORTS_VIEW, PERMISSIONS.IMPORTS_APPROVE,
    PERMISSIONS.EXPORTS_VIEW, PERMISSIONS.EXPORTS_CREATE, PERMISSIONS.EXPORTS_APPROVE, PERMISSIONS.EXPORTS_COMPLETE, PERMISSIONS.EXPORTS_CANCEL,
    PERMISSIONS.STOCK_CHECK_VIEW, PERMISSIONS.STOCK_CHECK_CREATE, PERMISSIONS.STOCK_CHECK_APPROVE, PERMISSIONS.STOCK_CHECK_ADJUST, PERMISSIONS.STOCK_CHECK_CANCEL,
    PERMISSIONS.QUALITY_CHECK_VIEW, PERMISSIONS.QUALITY_CHECK_CREATE, PERMISSIONS.QUALITY_CHECK_UPDATE, PERMISSIONS.QUALITY_CHECK_START, PERMISSIONS.QUALITY_CHECK_RECORD_DEFECT, PERMISSIONS.QUALITY_CHECK_COMPLETE, PERMISSIONS.QUALITY_CHECK_ADJUST, PERMISSIONS.QUALITY_CHECK_CANCEL, PERMISSIONS.QUALITY_CHECK_REVIEW, PERMISSIONS.QUALITY_CHECK_RESOLVE,
    PERMISSIONS.REPORTS_VIEW, PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.REPORT_INVENTORY, PERMISSIONS.REPORT_IMPORT, PERMISSIONS.REPORT_EXPORT, PERMISSIONS.REPORT_STOCK_CHECK, PERMISSIONS.REPORT_QUALITY, PERMISSIONS.REPORT_SUPPLIER, PERMISSIONS.REPORT_PART, PERMISSIONS.REPORT_WAREHOUSE,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.ROLES_VIEW,
    PERMISSIONS.AUDIT_LOGS_VIEW,
  ],
  
  'Warehouse Staff': [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PARTS_VIEW, PERMISSIONS.PARTS_CREATE, PERMISSIONS.PARTS_UPDATE,
    PERMISSIONS.CATEGORIES_VIEW,
    PERMISSIONS.SUPPLIERS_VIEW,
    PERMISSIONS.WAREHOUSES_VIEW,
    PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.IMPORTS_VIEW, PERMISSIONS.IMPORTS_CREATE, PERMISSIONS.IMPORTS_COMPLETE,
    PERMISSIONS.EXPORTS_VIEW, PERMISSIONS.EXPORTS_CREATE, PERMISSIONS.EXPORTS_COMPLETE, PERMISSIONS.EXPORTS_CANCEL,
    PERMISSIONS.STOCK_CHECK_VIEW, PERMISSIONS.STOCK_CHECK_CREATE, PERMISSIONS.STOCK_CHECK_COUNT, PERMISSIONS.STOCK_CHECK_COMPLETE, PERMISSIONS.STOCK_CHECK_CANCEL,
    PERMISSIONS.QUALITY_CHECK_VIEW, PERMISSIONS.QUALITY_CHECK_CREATE, PERMISSIONS.QUALITY_CHECK_START, PERMISSIONS.QUALITY_CHECK_RECORD_DEFECT, PERMISSIONS.QUALITY_CHECK_COMPLETE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORT_INVENTORY, PERMISSIONS.REPORT_WAREHOUSE, PERMISSIONS.REPORT_IMPORT, PERMISSIONS.REPORT_EXPORT, PERMISSIONS.REPORT_STOCK_CHECK,
  ],
  
  'Assembly Staff': [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PARTS_VIEW,
    PERMISSIONS.CATEGORIES_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.EXPORTS_VIEW, PERMISSIONS.EXPORTS_CREATE, // Request Export
    PERMISSIONS.QUALITY_CHECK_VIEW, PERMISSIONS.QUALITY_CHECK_CREATE, // Report Defect
  ],
  
  'QC Staff': [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PARTS_VIEW,
    PERMISSIONS.CATEGORIES_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.IMPORTS_VIEW, // View Inbound QC
    PERMISSIONS.QUALITY_CHECK_VIEW, PERMISSIONS.QUALITY_CHECK_CREATE, PERMISSIONS.QUALITY_CHECK_UPDATE, PERMISSIONS.QUALITY_CHECK_START, PERMISSIONS.QUALITY_CHECK_RECORD_DEFECT, PERMISSIONS.QUALITY_CHECK_COMPLETE, PERMISSIONS.QUALITY_CHECK_CANCEL, PERMISSIONS.QUALITY_CHECK_REVIEW, PERMISSIONS.QUALITY_CHECK_RESOLVE,
    PERMISSIONS.REPORTS_VIEW, // Quality Reports
    PERMISSIONS.REPORT_QUALITY, PERMISSIONS.REPORT_INVENTORY,
  ],
};

export function hasPermission(userPermissions: string[] | string | undefined | null, requiredPermission: string): boolean {
  if (!userPermissions) return false;
  if (Array.isArray(userPermissions)) {
    if (userPermissions.includes(requiredPermission)) return true;
    if (requiredPermission === PERMISSIONS.REPORT_INVENTORY && userPermissions.includes(PERMISSIONS.REPORTS_VIEW)) {
      return true;
    }
    return false;
  }
  if (typeof userPermissions === 'string') {
    try {
      const parsed = JSON.parse(userPermissions);
      if (Array.isArray(parsed)) {
        if (parsed.includes(requiredPermission)) return true;
        if (requiredPermission === PERMISSIONS.REPORT_INVENTORY && parsed.includes(PERMISSIONS.REPORTS_VIEW)) {
          return true;
        }
        return false;
      }
    } catch {}
    return userPermissions.includes(requiredPermission);
  }
  return false;
}
